from pathlib import Path
import base64
import io
import zipfile

ROOT = Path(__file__).resolve().parent
encoded = "".join(p.read_text(encoding="ascii") for p in sorted((ROOT / "payload_parts").glob("part_*.b64")))
with zipfile.ZipFile(io.BytesIO(base64.b64decode(encoded))) as bundle:
    source = bundle.read("site.py").decode("utf-8")
    ASSET_BYTES = {Path(name).name: bundle.read(name) for name in bundle.namelist() if name.startswith("assets/")}

# Publish the complete "Leading in the AI Enterprise" article series in the
# Blog section without repacking the embedded site bundle.
_blog_anchor = '''              <div class="beliefs">\n                <article class="belief"><span class="num">01</span><p>“A portfolio with twenty pilots and no stopping rules is not an AI strategy.”</p></article>'''
_series_block = '''              <section style="margin:44px 0 58px;">
                <div style="display:flex;justify-content:space-between;gap:24px;align-items:end;flex-wrap:wrap;margin-bottom:24px;">
                  <div style="max-width:760px;">
                    <p class="kicker" style="margin-bottom:10px;">Leading in the AI Enterprise</p>
                    <h3 style="font-family:Georgia,serif;font-size:clamp(30px,4vw,48px);font-weight:500;line-height:1.08;margin:0 0 12px;">18 essays on what enterprise AI leadership looks like in practice.</h3>
                    <p style="font-size:17px;line-height:1.65;color:#505653;margin:0;">A chronological series on strategy, value, operating models, governance, workforce, risk and the practical choices that determine whether AI becomes real capability or remains a collection of experiments.</p>
                  </div>
                  <div style="font-size:13px;letter-spacing:.09em;text-transform:uppercase;color:#6c716e;white-space:nowrap;">Series · 18 articles</div>
                </div>

                <div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:14px;">
                  <a href="https://lnkd.in/eFNiAX8M" target="_blank" rel="noopener noreferrer" style="text-decoration:none;color:inherit;border:1px solid rgba(16,19,26,.14);background:#fffdf9;padding:22px;display:block;"><span style="font-size:12px;letter-spacing:.12em;color:#8a8f8b;">01</span><div style="font-size:20px;font-family:Georgia,serif;margin-top:20px;">Strategy Alignment</div><div style="margin-top:16px;font-size:13px;">Read article ↗</div></a>
                  <a href="https://lnkd.in/ekQqQdgf" target="_blank" rel="noopener noreferrer" style="text-decoration:none;color:inherit;border:1px solid rgba(16,19,26,.14);background:#fffdf9;padding:22px;display:block;"><span style="font-size:12px;letter-spacing:.12em;color:#8a8f8b;">02</span><div style="font-size:20px;font-family:Georgia,serif;margin-top:20px;">ROI</div><div style="margin-top:16px;font-size:13px;">Read article ↗</div></a>
                  <a href="https://lnkd.in/e7yrc6zh" target="_blank" rel="noopener noreferrer" style="text-decoration:none;color:inherit;border:1px solid rgba(16,19,26,.14);background:#fffdf9;padding:22px;display:block;"><span style="font-size:12px;letter-spacing:.12em;color:#8a8f8b;">03</span><div style="font-size:20px;font-family:Georgia,serif;margin-top:20px;">Operating Model</div><div style="margin-top:16px;font-size:13px;">Read article ↗</div></a>
                  <a href="https://lnkd.in/eJ8EHKHQ" target="_blank" rel="noopener noreferrer" style="text-decoration:none;color:inherit;border:1px solid rgba(16,19,26,.14);background:#fffdf9;padding:22px;display:block;"><span style="font-size:12px;letter-spacing:.12em;color:#8a8f8b;">04</span><div style="font-size:20px;font-family:Georgia,serif;margin-top:20px;">AI Governance</div><div style="margin-top:16px;font-size:13px;">Read article ↗</div></a>
                  <a href="https://lnkd.in/ezmrefxC" target="_blank" rel="noopener noreferrer" style="text-decoration:none;color:inherit;border:1px solid rgba(16,19,26,.14);background:#fffdf9;padding:22px;display:block;"><span style="font-size:12px;letter-spacing:.12em;color:#8a8f8b;">05</span><div style="font-size:20px;font-family:Georgia,serif;margin-top:20px;">Data Readiness</div><div style="margin-top:16px;font-size:13px;">Read article ↗</div></a>
                  <a href="https://lnkd.in/ebYBiuyH" target="_blank" rel="noopener noreferrer" style="text-decoration:none;color:inherit;border:1px solid rgba(16,19,26,.14);background:#fffdf9;padding:22px;display:block;"><span style="font-size:12px;letter-spacing:.12em;color:#8a8f8b;">06</span><div style="font-size:20px;font-family:Georgia,serif;margin-top:20px;">Workforce Redesign</div><div style="margin-top:16px;font-size:13px;">Read article ↗</div></a>
                  <a href="https://lnkd.in/ez9xAzWb" target="_blank" rel="noopener noreferrer" style="text-decoration:none;color:inherit;border:1px solid rgba(16,19,26,.14);background:#fffdf9;padding:22px;display:block;"><span style="font-size:12px;letter-spacing:.12em;color:#8a8f8b;">07</span><div style="font-size:20px;font-family:Georgia,serif;margin-top:20px;">Talent &amp; Upskilling</div><div style="margin-top:16px;font-size:13px;">Read article ↗</div></a>
                  <a href="https://lnkd.in/ew5mtJKv" target="_blank" rel="noopener noreferrer" style="text-decoration:none;color:inherit;border:1px solid rgba(16,19,26,.14);background:#fffdf9;padding:22px;display:block;"><span style="font-size:12px;letter-spacing:.12em;color:#8a8f8b;">08</span><div style="font-size:20px;font-family:Georgia,serif;margin-top:20px;">Change Management</div><div style="margin-top:16px;font-size:13px;">Read article ↗</div></a>
                  <a href="https://lnkd.in/dSZXXP5i" target="_blank" rel="noopener noreferrer" style="text-decoration:none;color:inherit;border:1px solid rgba(16,19,26,.14);background:#fffdf9;padding:22px;display:block;"><span style="font-size:12px;letter-spacing:.12em;color:#8a8f8b;">09</span><div style="font-size:20px;font-family:Georgia,serif;margin-top:20px;">Board AI Literacy</div><div style="margin-top:16px;font-size:13px;">Read article ↗</div></a>
                  <a href="https://lnkd.in/dYmKgQCi" target="_blank" rel="noopener noreferrer" style="text-decoration:none;color:inherit;border:1px solid rgba(16,19,26,.14);background:#fffdf9;padding:22px;display:block;"><span style="font-size:12px;letter-spacing:.12em;color:#8a8f8b;">10</span><div style="font-size:20px;font-family:Georgia,serif;margin-top:20px;">Agentic AI</div><div style="margin-top:16px;font-size:13px;">Read article ↗</div></a>
                  <a href="https://lnkd.in/dJUbX98E" target="_blank" rel="noopener noreferrer" style="text-decoration:none;color:inherit;border:1px solid rgba(16,19,26,.14);background:#fffdf9;padding:22px;display:block;"><span style="font-size:12px;letter-spacing:.12em;color:#8a8f8b;">11</span><div style="font-size:20px;font-family:Georgia,serif;margin-top:20px;">Human Oversight</div><div style="margin-top:16px;font-size:13px;">Read article ↗</div></a>
                  <a href="https://lnkd.in/dzk9dQxK" target="_blank" rel="noopener noreferrer" style="text-decoration:none;color:inherit;border:1px solid rgba(16,19,26,.14);background:#fffdf9;padding:22px;display:block;"><span style="font-size:12px;letter-spacing:.12em;color:#8a8f8b;">12</span><div style="font-size:20px;font-family:Georgia,serif;margin-top:20px;">Regulation &amp; Compliance</div><div style="margin-top:16px;font-size:13px;">Read article ↗</div></a>
                  <a href="https://lnkd.in/deKcUfeS" target="_blank" rel="noopener noreferrer" style="text-decoration:none;color:inherit;border:1px solid rgba(16,19,26,.14);background:#fffdf9;padding:22px;display:block;"><span style="font-size:12px;letter-spacing:.12em;color:#8a8f8b;">13</span><div style="font-size:20px;font-family:Georgia,serif;margin-top:20px;">Cybersecurity &amp; AI</div><div style="margin-top:16px;font-size:13px;">Read article ↗</div></a>
                  <a href="https://lnkd.in/emV6E-Qe" target="_blank" rel="noopener noreferrer" style="text-decoration:none;color:inherit;border:1px solid rgba(16,19,26,.14);background:#fffdf9;padding:22px;display:block;"><span style="font-size:12px;letter-spacing:.12em;color:#8a8f8b;">14</span><div style="font-size:20px;font-family:Georgia,serif;margin-top:20px;">Shadow AI</div><div style="margin-top:16px;font-size:13px;">Read article ↗</div></a>
                  <a href="https://lnkd.in/e3-Qp9FT" target="_blank" rel="noopener noreferrer" style="text-decoration:none;color:inherit;border:1px solid rgba(16,19,26,.14);background:#fffdf9;padding:22px;display:block;"><span style="font-size:12px;letter-spacing:.12em;color:#8a8f8b;">15</span><div style="font-size:20px;font-family:Georgia,serif;margin-top:20px;">Responsible AI</div><div style="margin-top:16px;font-size:13px;">Read article ↗</div></a>
                  <a href="https://lnkd.in/ePdGggA3" target="_blank" rel="noopener noreferrer" style="text-decoration:none;color:inherit;border:1px solid rgba(16,19,26,.14);background:#fffdf9;padding:22px;display:block;"><span style="font-size:12px;letter-spacing:.12em;color:#8a8f8b;">16</span><div style="font-size:20px;font-family:Georgia,serif;margin-top:20px;">Competitive Intelligence</div><div style="margin-top:16px;font-size:13px;">Read article ↗</div></a>
                  <a href="https://lnkd.in/e6XN_wsn" target="_blank" rel="noopener noreferrer" style="text-decoration:none;color:inherit;border:1px solid rgba(16,19,26,.14);background:#fffdf9;padding:22px;display:block;"><span style="font-size:12px;letter-spacing:.12em;color:#8a8f8b;">17</span><div style="font-size:20px;font-family:Georgia,serif;margin-top:20px;">Tool Sprawl</div><div style="margin-top:16px;font-size:13px;">Read article ↗</div></a>
                  <a href="https://lnkd.in/eTZjFnbz" target="_blank" rel="noopener noreferrer" style="text-decoration:none;color:inherit;border:1px solid rgba(16,19,26,.14);background:#fffdf9;padding:22px;display:block;"><span style="font-size:12px;letter-spacing:.12em;color:#8a8f8b;">18</span><div style="font-size:20px;font-family:Georgia,serif;margin-top:20px;">AI Procurement</div><div style="margin-top:16px;font-size:13px;">Read article ↗</div></a>
                </div>
              </section>
              <div class="beliefs">
                <article class="belief"><span class="num">01</span><p>“A portfolio with twenty pilots and no stopping rules is not an AI strategy.”</p></article>'''
if _blog_anchor in source:
    source = source.replace(_blog_anchor, _series_block, 1)

exec(compile(source, "site_app.py", "exec"), globals(), globals())
