from __future__ import annotations

from site_assets import CV_URI, EMAIL, LINKEDIN, HERO_URI
from site_components import nav, footer


def contact() -> str:
    cv = f'<a href="{CV_URI}" download="Jair_Ribeiro_Master_CV_2026.pdf" data-hq-event="cv_download_contact">Download CV ↓</a>' if CV_URI else ""
    return f'''{nav("contact")}<main><section class="pagehero"><div class="container"><p class="eyebrow">Contact</p><h1>Discuss a leadership opportunity.</h1><p>If you are building or reshaping an AI, data or analytics capability and see a potential fit with my experience, I’m always interested in a good conversation.</p></div></section><section class="section paper"><div class="container contactgrid"><div><p class="eyebrow">Where the fit is strongest</p><h2>Senior mandates where AI and data have to move beyond experimentation.</h2><p>My focus is on leadership situations that combine enterprise AI or data strategy with operating capability, portfolio choices, governance, adoption and business value. I am most useful when the organization already has ambition and activity, but needs clearer priorities, ownership and a credible way to move from promising work to repeatable capability.</p><div class="focus"><div>Senior AI, Data &amp; Analytics leadership</div><div>AI transformation, adoption and capability</div><div>AI / Data operating models and Centers of Excellence</div><div>Responsible AI and governance with enterprise scope</div><div>Business-driven AI and selected management-consulting leadership</div></div><p>Based in Gothenburg, Sweden. Working across Sweden and international environments.</p></div><aside class="contactcard"><span>Direct contact</span><a href="mailto:{EMAIL}" data-hq-event="email_contact">{EMAIL}</a><a href="{LINKEDIN}" target="_blank" rel="noopener" data-hq-event="linkedin_contact">LinkedIn ↗</a>{cv}<p>Email or LinkedIn is the easiest way to reach me.</p></aside></div></section><section class="section white"><div class="container contactvisual"><div><p class="eyebrow">A useful first conversation</p><h2>Start with the mandate, not a job title.</h2><p>The most useful context is what the organization is trying to change, where the current AI or data capability is getting stuck, and what leadership accountability the role is expected to carry. That is usually enough to establish quickly whether my experience is relevant.</p></div><div class="contactportrait"><img src="{HERO_URI}" alt="Jair Ribeiro" loading="lazy" decoding="async"></div></div></section></main>{footer()}'''
