from __future__ import annotations

import html
from site_assets import PROFILE_URI, SPEAKING_URI, CV_URI, LINKEDIN, EMAIL
from site_components import nav, footer, opportunity, VALUES, THOUGHTS, card_grid, thought_grid

def home() -> str:
    cv = f'<a class="btn ghost" href="{CV_URI}" download="Jair_Ribeiro_Master_CV_2026.pdf">Download CV ↓</a>' if CV_URI else ""
    return f'''{nav("home")}<main>
<section class="hero"><div class="container heroin"><div><p class="eyebrow">Enterprise AI · Data · Analytics</p><h1>Jair Ribeiro<span>Senior AI &amp; Data Leader</span></h1><p class="deck">I help enterprises move from AI ambition and scattered experimentation to governed, adopted capabilities that create measurable business value.</p><p class="context">Strategy · AI portfolios · operating models · data foundations · governance · adoption · Gothenburg, Sweden · Sweden / International</p><div class="actions"><a class="btn primary" href="?page=impact" target="_self">View leadership impact →</a>{cv}<a class="btn text" href="?page=contact" target="_self">Discuss a leadership opportunity</a></div></div><div class="portrait"><img src="{PROFILE_URI}" alt="Jair Ribeiro"><div class="note"><span>Leadership focus</span><strong>Making AI useful, trusted, scalable and connected to the outcomes the business actually cares about.</strong></div></div></div><div class="company"><div class="container"><span>Experience across</span><b>Volvo Group</b><b>MSX International</b><b>Kimberly-Clark</b><b>IBM</b><b>HPE</b></div></div></section>
<section class="section white"><div class="container"><p class="eyebrow">Evidence before adjectives</p><div class="metrics"><div class="metric"><strong>100+</strong><p>AI initiatives and proofs of concept shaped across global markets and business functions.</p></div><div class="metric"><strong>1,000+</strong><p>Employees reached through practical AI literacy and adoption programs.</p></div><div class="metric"><strong>1,500+</strong><p>Practitioners engaged through enterprise AI communities and learning activity.</p></div><div class="metric"><strong>15+ yrs</strong><p>Across enterprise technology, data, analytics and AI environments.</p></div></div></div></section>
<section class="section paper"><div class="container"><div class="head"><div><p class="eyebrow">Where I create value</p><h2>The work between AI ambition and enterprise reality.</h2></div><p>My strongest work sits where business priorities, technology, data, governance and people have to move together. The goal is not more AI activity; it is better choices and repeatable capability.</p></div><div class="grid3">{card_grid(VALUES)}</div></div></section>
<section class="section navy"><div class="container"><div class="head"><div><p class="eyebrow">My enterprise AI lens</p><h2>AI scales as a system, not as a model.</h2></div><p>Strong technology is necessary. It is rarely sufficient. Enterprise value depends on how priorities, architecture, governance, adoption and accountability connect.</p></div><div class="flow"><div class="step"><span>01</span><strong>Business priorities</strong></div><div class="step"><span>02</span><strong>Opportunity portfolio</strong></div><div class="step"><span>03</span><strong>Data &amp; architecture</strong></div><div class="step"><span>04</span><strong>Governance</strong></div><div class="step"><span>05</span><strong>Adoption</strong></div><div class="step"><span>06</span><strong>Value &amp; scale</strong></div></div><p class="flowcopy">This is also how I approach leadership: connect the system, make trade-offs explicit, create enough structure for decisions and keep expert judgment close to the work.</p></div></section>
<section class="section white"><div class="container"><div class="head"><div><p class="eyebrow">Selected leadership impact</p><h2>Enterprise AI from strategy into operating capability.</h2></div><p>Leadership situations rather than project showcases: the operating problem, the choices made and the evidence that matters.</p></div><div class="grid3"><article class="card"><span class="org">MSX International</span><h3>AI &amp; Data CoE foundations</h3><p>Structured a business-facing CoE connecting AI portfolio management, data governance, responsible adoption and business engagement.</p><div class="proof">Portfolio visibility · prioritization · lifecycle ownership · trusted data practices</div></article><article class="card"><span class="org">Volvo Group / Volvo Trucks</span><h3>Enterprise AI adoption</h3><p>Led AI and analytics adoption across warranty, sales and aftermarket, translating business needs into practical use cases and adoption paths.</p><div class="proof">100+ initiatives / PoCs · 1,000+ employees reached</div></article><article class="card"><span class="org">Kimberly-Clark</span><h3>EMEA AI value discovery</h3><p>Connected data-science opportunities with business priorities across manufacturing, supply chain, logistics, sales and marketing.</p><div class="proof">Regional business translation · value discovery · portfolio shaping</div></article></div><div class="actions"><a class="btn dark" href="?page=impact" target="_self">Explore the cases →</a></div></div></section>
<section class="section soft"><div class="container"><div class="head"><div><p class="eyebrow">How I lead</p><h2>Collaborative in understanding. Clear when decisions need to be made.</h2></div><p>I work best where useful disagreement, cross-functional ownership and practical judgment matter more than AI theatre.</p></div><div class="principles"><div class="principle"><span>01</span><h3>Make complexity understandable</h3><p>Create enough structure for teams to decide without turning AI into bureaucracy.</p></div><div class="principle"><span>02</span><h3>Work across boundaries</h3><p>Most AI problems sit between business, data, technology, governance and people. I am comfortable in those seams.</p></div><div class="principle"><span>03</span><h3>Challenge without theatre</h3><p>Prefer evidence, clear trade-offs and useful disagreement over hype or false certainty.</p></div><div class="principle"><span>04</span><h3>Build capability, not dependency</h3><p>Help the organization become increasingly capable of acting for itself.</p></div></div></div></section>
<section class="section white"><div class="container twocol"><div><p class="eyebrow">Technical &amp; enterprise fluency</p><h2>Enough depth to challenge trade-offs. Enough perspective to know when specialist depth is required.</h2></div><div><div class="chips"><span>Enterprise AI architecture</span><span>GenAI</span><span>Agentic AI</span><span>Analytics</span><span>Data platforms</span><span>Data quality</span><span>Stewardship</span><span>Cloud</span><span>MLOps principles</span><span>Security</span><span>AI risk</span><span>Governance</span><span>Scalability</span><span>Vendor evaluation</span><span>Cost / accuracy trade-offs</span><span>Operational readiness</span></div><p class="muted">My background spans enterprise infrastructure, cloud, IBM Watson solution design, analytics, data and AI. That foundation helps me lead specialists, challenge assumptions and connect technical choices to business, governance and adoption consequences.</p></div></div></section>
<section class="section navy"><div class="container"><div class="head"><div><p class="eyebrow">Selected thinking</p><h2>Leading in the AI Enterprise</h2></div><p>A practical body of work about value, operating models, data, governance, workforce and responsible scale.</p></div>{thought_grid(THOUGHTS[:4])}<div class="actions"><a class="btn ghost" href="?page=thinking" target="_self">View selected thinking →</a></div></div></section>
<section class="section paper"><div class="container speak"><img src="{SPEAKING_URI}" alt="Jair Ribeiro speaking on an industry panel"><div><p class="eyebrow">In the room</p><h2>Turning complex AI questions into conversations leaders can act on.</h2><p>I have worked across executive, business and technical audiences in global organizations and industry settings. The communication challenge is often the same: remove unnecessary complexity without removing the trade-offs that matter.</p><div class="prooflist"><div class="proofitem"><strong>Thinkers360</strong> — Top 50 Global Thought Leaders &amp; Influencers on Emerging Technology (2023).</div><div class="proofitem"><strong>Generative AI Summit, London</strong> — keynote on strategies for scaling AI adoption across the enterprise.</div><div class="proofitem"><strong>Published work</strong> — enterprise AI leadership, governance, operating models, data readiness, adoption and responsible AI.</div></div></div></div></section>{opportunity()}</main>{footer()}'''
