from __future__ import annotations

import html
from site_components import nav, footer, opportunity

def case(org: str, role: str, date: str, title: str, intro: str, boxes: list[tuple[str,str]]) -> str:
    box_html = "".join(f'<div class="box"><span>{html.escape(k)}</span><p>{html.escape(v)}</p></div>' for k,v in boxes)
    return f'<article class="case"><div class="casemeta"><div class="org">{html.escape(org)}</div><strong>{html.escape(role)}</strong><span>{html.escape(date)}</span></div><div><h2>{html.escape(title)}</h2><p>{html.escape(intro)}</p><div class="caseboxes">{box_html}</div></div></article>'


def impact() -> str:
    cases = [
        case("MSX International","AI & Data Center of Excellence Director","Dec 2025 – Jun 2026 · Gothenburg","Creating an operating foundation around a fragmented AI and data agenda.","The mandate sat across AI portfolio management, data governance, responsible adoption and business engagement. The work was less about producing another strategy document and more about creating structures for clearer decisions.",[("Context","Multiple AI opportunities and data topics needed clearer visibility, prioritization, ownership and readiness criteria."),("Leadership choices","Connected portfolio logic, lifecycle stages, ownership, risk-aware criteria and data stewardship foundations."),("What changed","Improved portfolio visibility and prioritization, clearer lifecycle discipline and stronger foundations for data ownership, quality and responsible scale.")]),
        case("Volvo Group / Volvo Trucks","Data Analytics & AI Leader","Aug 2022 – Dec 2025 · Gothenburg","Making enterprise AI practical across commercial operations.","AI adoption in a global industrial company requires translation between business owners, Digital & IT, analytics specialists, governance stakeholders and partners while keeping value and adoption close to operational work.",[("Context","Warranty, sales and aftermarket teams needed practical paths to explore AI within enterprise technology and governance constraints."),("Leadership choices","Used portfolio thinking, cross-functional collaboration, literacy and business translation to connect opportunities with credible adoption paths."),("Evidence","Managed 100+ AI ideas and PoCs and designed literacy/adoption activity reaching 1,000+ employees.")]),
        case("Kimberly-Clark","AI Strategist – EMEA","Jul 2021 – Sep 2022 · EMEA","Connecting AI opportunity discovery to business priorities across EMEA.","The role focused on value discovery and realization: helping functions identify where AI and data science could matter and translating opportunities into a form business and technical stakeholders could work with together.",[("Context","Functions had different problems, data realities and readiness levels."),("Leadership choices","Worked across supply chain, manufacturing, sales, marketing and logistics to shape practical opportunities around business priorities."),("What it demonstrates","Regional portfolio thinking, value discovery and translation between domain leaders and data-science teams.")]),
        case("Volvo Group + IBM / earlier career","AI business expert · Watson solution design · enterprise technology","2004 – 2021 · International","A technical foundation underneath today’s leadership work.","Before senior enterprise AI leadership, my work spanned infrastructure, cloud, enterprise systems, IBM Watson solution design, consulting and client-facing technology delivery. That matters because AI decisions are rarely isolated from architecture and operational constraints.",[("Scale","Supported 100+ AI initiatives and delivered 100+ learning sessions in earlier Volvo AI roles."),("Community","Engaged a practitioner network involving 1,500+ people across regions."),("Technical fluency","Cloud, infrastructure, Watson solution design and technology consulting provide the base for challenging technical trade-offs today.")]),
    ]
    return f'''{nav("impact")}<main><section class="pagehero"><div class="container"><p class="eyebrow">Leadership impact</p><h1>How I turn AI ambition into operating capability.</h1><p>Selected situations where the leadership problem was broader than technology: portfolio choices, ownership, governance, adoption, data readiness and the ability to scale responsibly.</p></div></section><section class="section paper"><div class="container">{"".join(cases)}</div></section><section class="section navy"><div class="container"><div class="head"><div><p class="eyebrow">Recurring trade-offs</p><h2>Senior AI leadership is decision quality under competing constraints.</h2></div><p>I prefer to make these tensions explicit early rather than let them surface later as delivery problems.</p></div><div class="flow"><div class="step"><span>01</span><strong>Speed ↔ governance</strong></div><div class="step"><span>02</span><strong>Experiment ↔ scale</strong></div><div class="step"><span>03</span><strong>Central ↔ federated</strong></div><div class="step"><span>04</span><strong>Ambition ↔ data maturity</strong></div><div class="step"><span>05</span><strong>Sophistication ↔ adoption</strong></div><div class="step"><span>06</span><strong>Volume ↔ investment focus</strong></div></div></div></section>{opportunity()}</main>{footer()}'''
