from __future__ import annotations

"""Final public-delivery override for the downloadable CV.

The canonical PDF is generated by site_cv_patch into Streamlit's static folder.
Use that same-origin static URL for every CV CTA instead of a large data URI.
The static URL remains a normal clickable anchor and allows the HTML download
attribute to work reliably across the footer, About, Contact and role lenses.
"""

import site_assets as assets

CV_FILENAME = "Jair_Ribeiro_Senior_AI_Data_Leader_CV_2026.pdf"
assets.CV_URI = f"/app/static/{CV_FILENAME}"
