from __future__ import annotations

from site_assets import CV_URI, ABOUT_BW_URI
from site_components import nav, footer, opportunity


def about() -> str:
    cv = f'<a class="btn dark" href="{CV_URI}" download="Jair_Ribeiro_Master_CV_2026.pdf" data-hq-event="cv_download_about">Download full CV ↓</a>' if CV_URI else ""
    return f'''{nav("about")}<main>
<section class="pagehero"><div class="container"><p class="eyebrow">About</p><h1>A career built at the intersection of technology, business and enterprise change.</h1><p>More than 15 years across enterprise technology, data, analytics and AI — moving progressively from technical foundations into business-facing AI leadership.</p></div></section>

<section class="section white"><div class="container editorial-split"><div><p class="eyebrow">Professional arc</p><h2>From enterprise technology foundations to AI operating capability.</h2><p class="muted">The common thread is not a single technology. It is helping organizations make better decisions around AI: where to focus, what has to be true before scaling, how ownership should work, and how technical possibility connects to real business behavior.</p><p class="muted">My earlier career built a practical base across enterprise systems, infrastructure, cloud, consulting and IBM Watson solution design. That work taught me that technology decisions are never only technical: they carry cost, operating, risk and stakeholder consequences that become more visible as solutions move toward production.</p><p class="muted">From there, my work shifted toward the business side of AI — use-case discovery, product and portfolio leadership, analytics, enterprise adoption, governance and operating models. At Volvo Group and Volvo Trucks, I worked across AI initiatives, commercial operations, literacy and adoption. At Kimberly-Clark, I led AI value discovery across EMEA. Most recently at MSX International, I established foundations for a business-facing AI &amp; Data CoE spanning portfolio governance, data governance, responsible adoption and scale-readiness.</p><p class="muted">My current focus is on senior leadership mandates where enterprise AI, data, governance, adoption and operating-model design come together — particularly in organizations moving from experimentation toward repeatable business capability.</p></div><div class="editorial-photo portrait"><img src="{ABOUT_BW_URI}" alt="Jair Ribeiro portrait" loading="lazy" decoding="async"></div></div><div class="container"><div class="timeline"><div class="trow"><b>2025–2026</b><div><strong>MSX International</strong><span>AI &amp; Data Center of Excellence Director · Gothenburg</span></div></div><div class="trow"><b>2022–2025</b><div><strong>Volvo Group / Volvo Trucks</strong><span>Data Analytics &amp; AI Leader · Gothenburg</span></div></div><div class="trow"><b>2021–2022</b><div><strong>Kimberly-Clark</strong><span>AI Strategist – EMEA · Wroclaw, Poland</span></div></div><div class="trow"><b>2018–2021</b><div><strong>Volvo Group</strong><span>Senior AI Business Expert · Wroclaw, Poland</span></div></div><div class="trow"><b>2004–2018</b><div><strong>IBM, HPE and earlier roles</strong><span>AI, cloud, IT consulting, infrastructure and enterprise systems · Milan, Italy</span></div></div></div></div></section>

<section class="section soft"><div class="container"><div class="head"><div><p class="eyebrow">How I lead</p><h2>Collaborative in understanding. Clear when decisions need to be made.</h2></div><p>I do not see collaboration and decisiveness as opposites. Good AI leadership creates enough shared understanding for specialists to challenge each other, then makes ownership and the next decision explicit.</p></div><div class="principles"><div class="principle"><span>01</span><h3>Make complexity understandable</h3><p>I separate what is known, what is assumed and what still needs to be proven. That gives teams enough structure to decide without turning uncertainty into bureaucracy.</p></div><div class="principle"><span>02</span><h3>Work across boundaries</h3><p>Most AI problems sit between business, data, technology, governance and people. I make ownership visible and translate the consequences of one discipline’s choices for the others.</p></div><div class="principle"><span>03</span><h3>Challenge without theatre</h3><p>I surface disagreement early, explain the trade-off and make a recommendation without pretending uncertainty has disappeared. Useful challenge is more valuable than artificial certainty.</p></div><div class="principle"><span>04</span><h3>Build capability, not dependency</h3><p>I prefer reusable patterns, clear decision rights and stronger internal judgment over a central team that has to approve or deliver everything. Scale improves when the organization learns to act for itself.</p></div></div></div></section>

<section class="section navy"><div class="container"><div class="head"><div><p class="eyebrow">Enterprise AI operating lens</p><h2>AI scales as a system, not as a model.</h2></div><p>Strong technology is necessary. It is rarely sufficient. Enterprise value depends on the quality of the connections around it: what problem is being solved, what data and architecture can support it, what risks have to be managed, who will use it and who is accountable for the result.</p></div><div class="flow"><div class="step"><span>01</span><strong>Business priorities</strong></div><div class="step"><span>02</span><strong>Opportunity portfolio</strong></div><div class="step"><span>03</span><strong>Data &amp; architecture</strong></div><div class="step"><span>04</span><strong>Governance</strong></div><div class="step"><span>05</span><strong>Adoption</strong></div><div class="step"><span>06</span><strong>Value &amp; scale</strong></div></div><p class="flowcopy">Each step changes the quality of the next. Weak business framing creates a noisy portfolio. Weak data and architecture turn good ideas into exceptions. Weak governance creates uncertainty. Weak adoption leaves technically sound solutions unused. I use this sequence as a diagnostic lens, not as a rigid methodology: the point is to find where the system is breaking and make the next decision clearer.</p></div></section>

<section class="section white"><div class="container twocol"><div><p class="eyebrow">Technical &amp; enterprise fluency</p><h2>Technical depth in service of better leadership decisions.</h2><p class="muted">I am not positioning myself as the deepest engineer in the room. My responsibility is to understand enough of the system to ask the right questions, challenge trade-offs and know when specialist depth must drive the decision. The credibility I want to demonstrate is technical judgment: reasoning about architecture, data, security, MLOps, economics and scalability well enough to make better leadership decisions — not coding theatre or isolated technical demos.</p></div><div><div class="chips"><span>Enterprise AI architecture</span><span>GenAI</span><span>Agentic AI</span><span>Analytics</span><span>Data platforms</span><span>Data quality</span><span>Stewardship</span><span>Cloud</span><span>MLOps principles</span><span>Security</span><span>AI risk</span><span>Governance</span><span>Scalability</span><span>Vendor evaluation</span><span>Cost / accuracy trade-offs</span><span>Operational readiness</span></div><div class="grid3" style="margin-top:24px"><article class="card"><span class="org">Architecture</span><h3>Can this survive the enterprise?</h3><p>I look beyond model quality to integration, scalability, security, maintainability and the cost of turning a promising prototype into something the organization can operate.</p></article><article class="card"><span class="org">Data &amp; trust</span><h3>Is the foundation credible?</h3><p>Data access, quality, semantics, stewardship and lineage shape both technical performance and organizational trust. Weak foundations usually reappear later as adoption or governance problems.</p></article><article class="card"><span class="org">Risk &amp; economics</span><h3>Is the trade-off worth it?</h3><p>Accuracy, autonomy, cost, control and user value move together. The right question is rarely “Can we build it?” but “What level of capability is justified for this decision, user and risk?”</p></article></div></div></div></section>

<section class="section soft"><div class="container"><div class="head"><div><p class="eyebrow">Credentials &amp; perspective</p><h2>Formal study matters most when it sharpens practical judgment.</h2></div><p>My academic work complements rather than replaces operating experience. The focus has been on how AI can be adopted responsibly inside real organizations, where governance, trust, incentives and business pressure exist at the same time.</p></div><div class="grid3"><div class="card"><span class="org">Education</span><h3>MSc, Artificial Intelligence</h3><p>Research focused on Responsible AI adoption in global enterprises and the tension between innovation, governance and trust.</p></div><div class="card"><span class="org">Research lens</span><h3>Responsible adoption, not compliance theatre</h3><p>I am interested in governance as an operating capability: how ownership, evidence, risk and escalation can increase trust and decision quality without disconnecting control from the work.</p></div><div class="card"><span class="org">Recognition</span><h3>Thinkers360 Top 50</h3><p>Recognized among Global Thought Leaders &amp; Influencers on Emerging Technology in 2023. I treat recognition as external validation of the work, not as a professional title.</p></div></div></div></section>

<section class="section white"><div class="container"><div class="head"><div><p class="eyebrow">Languages &amp; working context</p><h2>International experience, with Sweden as the professional base.</h2></div><p>Based in Gothenburg, with experience across Sweden, Poland, Italy and Brazil and work in global organizations. That background has made me comfortable adapting how I communicate and lead without changing the standard of evidence or accountability behind the decision.</p></div><div class="chips"><span>Portuguese — native/bilingual</span><span>Italian — native/bilingual</span><span>English — full professional</span><span>Spanish — professional</span><span>Polish — limited working</span><span>Swedish — elementary</span></div><div class="actions">{cv}</div></div></section>

<section class="section navy"><div class="container"><div class="head"><div><p class="eyebrow">Shareable role lenses</p><h2>One leadership identity, viewed through three common mandates.</h2></div><p>These pages reorganize the same evidence around the roles a recruiter or hiring manager is most likely to consider me for.</p></div><div class="grid3"><a class="card" href="?page=enterprise" target="_self" style="text-decoration:none" data-hq-event="role_lens_enterprise"><span class="org">Role lens</span><h3>Data &amp; AI Leadership</h3><p>Head / Director mandates spanning AI, data, analytics, governance and enterprise capability.</p><div class="proof">Open lens →</div></a><a class="card" href="?page=transformation" target="_self" style="text-decoration:none" data-hq-event="role_lens_transformation"><span class="org">Role lens</span><h3>AI Transformation &amp; Adoption</h3><p>Turning AI ambition and experimentation into portfolios, operating capability and changed ways of working.</p><div class="proof">Open lens →</div></a><a class="card" href="?page=governance" target="_self" style="text-decoration:none" data-hq-event="role_lens_governance"><span class="org">Role lens</span><h3>AI Governance &amp; Operating Model</h3><p>Decision rights, lifecycle controls, responsible AI and governance mechanisms designed for scale.</p><div class="proof">Open lens →</div></a></div></div></section>
{opportunity()}</main>{footer()}'''
