from __future__ import annotations

from site_assets import CV_URI, HERO_URI, LINKEDIN
from site_components import nav, footer, CV_DOWNLOAD_NAME
from site_artifacts import framework_teaser


CLAES_LINKEDIN = "https://se.linkedin.com/in/claes-sandros-1a795512"
ANNA_LINKEDIN = "https://se.linkedin.com/in/annaborjesson"
KUMARA_LINKEDIN = "https://in.linkedin.com/in/kumara-datta"
JIM_LINKEDIN = "https://www.linkedin.com/in/james-edwards-7233b8152"


def home() -> str:
    return f'''{nav("home")}<main>
<section class="hero"><div class="container heroin"><div><p class="eyebrow">Enterprise AI · Data · Analytics</p><h1>Jair Ribeiro<span>Enterprise AI &amp; Data Leader</span></h1><p class="deck">I work at the point where enterprise AI strategy meets operating reality — connecting business priorities, portfolio choices, data, governance, adoption and measurable value.</p><p class="context" style="max-width:760px;margin-top:18px">AI scales as a system, not as a model. The difficult part is usually not proving that AI can work, but creating the conditions around it so the organization can use, trust and scale it.</p><p class="context">Based in Gothenburg · Sweden &amp; international mandates</p><div class="actions"><a class="btn primary" href="?page=impact" target="_self" data-hq-event="impact_home">View my impact →</a><a class="btn text" href="?page=contact" target="_self" data-hq-event="contact_home">Contact me</a><a class="btn text" href="{CV_URI}" download="{CV_DOWNLOAD_NAME}" data-hq-event="cv_download_home">Download my CV ↓</a></div></div><div class="portrait"><img src="{HERO_URI}" alt="Jair Ribeiro contributing to an executive AI panel" loading="eager" fetchpriority="high" decoding="async"><div class="note"><span>Leadership perspective</span><strong>The model is only one part of the outcome. The surrounding decisions determine whether AI becomes useful.</strong></div></div></div><div class="company"><div class="container"><span>Experience across</span><b>Volvo Group</b><b>MSX International</b><b>Kimberly-Clark</b><b>IBM</b><b>HPE</b></div></div></section>

<section class="section white"><div class="container"><div class="head"><div><p class="eyebrow">Scale of experience</p><h2>Enterprise technology depth, with eight years focused on AI, data and analytics leadership.</h2></div><p>My career spans infrastructure, cloud, consulting, data, analytics and AI, with 8+ years centered on turning AI opportunities into work the organization can support and use.</p></div><div class="prooflist"><div class="proofitem"><strong>20+ years</strong> — enterprise technology experience across infrastructure, cloud, consulting, data, analytics and AI.</div><div class="proofitem"><strong>100+ initiatives</strong> — across my Volvo AI roles, I shaped and supported 100+ AI initiatives, PoCs and projects.</div><div class="proofitem"><strong>1,000+ employees</strong> — reached through practical AI literacy and adoption activity at Volvo Trucks.</div><div class="proofitem"><strong>1,500+ practitioners</strong> — engaged through broader enterprise AI community and Center of Excellence activity at Volvo Group.</div></div></div></section>

<section class="section paper"><div class="container"><div class="head"><div><p class="eyebrow">Selected leadership cases</p><h2>From value discovery to adoption and enterprise AI &amp; Data foundations.</h2></div><p>Across these roles, the context changed but the underlying questions became increasingly connected: where AI is worth pursuing, how it fits real work, and what structures are needed around it.</p></div><div class="thoughts" style="grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr));gap:18px"><article class="card"><span class="org">Volvo Group / Volvo Trucks</span><h3>Connecting AI adoption with real business workflows.</h3><p><strong>Challenge:</strong> AI opportunities across commercial operations and enterprise communities sat inside different workflows, data conditions and stakeholder environments.</p><p><strong>What I shaped:</strong> I treated use-case work, literacy and adoption as connected problems, bringing business and Digital &amp; IT into the same conversation rather than measuring progress by pilot or training volume alone.</p><div class="proof">Commercial operations · use cases · literacy · business / Digital &amp; IT collaboration</div></article><article class="card"><span class="org">MSX International</span><h3>Building the foundations for an enterprise AI &amp; Data capability.</h3><p><strong>Challenge:</strong> An emerging CoE needed clearer portfolio visibility, decision rights, governance and data foundations while the organization was still building readiness.</p><p><strong>What I shaped:</strong> I introduced a small number of connected decision mechanisms rather than a heavy central control model the organization was not yet ready to absorb.</p><div class="proof">Lifecycle stages · decision rights · readiness criteria · stewardship foundations</div></article><article class="card"><span class="org">Kimberly-Clark</span><h3>Making EMEA AI opportunities comparable without losing context.</h3><p><strong>Challenge:</strong> Functions had different problems, data realities and readiness, making AI opportunities difficult to compare on a like-for-like basis.</p><p><strong>What I shaped:</strong> I started from the business problem and value hypothesis, adding enough structure to compare opportunities without allowing the method to replace the local business reality.</p><div class="proof">EMEA value discovery · opportunity comparison · business translation</div></article></div><div class="actions"><a class="btn dark" href="?page=impact" target="_self" data-hq-event="impact_cases">See the full leadership cases →</a></div></div></section>

<section class="section white"><div class="container"><div class="head"><div><p class="eyebrow">Leadership focus</p><h2>The enterprise AI problems that keep recurring.</h2></div><p>Different organizations express them differently, but the same questions keep returning: where to focus, how AI changes real work, where decisions belong and what has to be true before broader use.</p></div><div class="grid3"><a class="card" href="?page=enterprise" target="_self" data-hq-event="role_lens_enterprise_home" style="text-decoration:none"><span class="org">Enterprise AI &amp; Data Leadership</span><h3>Connect strategy with enterprise decisions.</h3><p>Strategy, portfolio, Data &amp; Analytics, operating models and the choices that turn priorities into executable work.</p><div class="proof">Explore context →</div></a><a class="card" href="?page=transformation" target="_self" data-hq-event="role_lens_transformation_home" style="text-decoration:none"><span class="org">AI Transformation &amp; Adoption</span><h3>Move from opportunity into sustained use.</h3><p>From opportunity selection and experimentation into real work, internal capability, workflow change and sustained use.</p><div class="proof">Explore context →</div></a><a class="card" href="?page=governance" target="_self" data-hq-event="role_lens_governance_home" style="text-decoration:none"><span class="org">Governance &amp; Responsible Scale</span><h3>Make responsibility, risk and readiness explicit.</h3><p>Decision rights, data responsibility, risk, evidence and the conditions that need to be met before broader use.</p><div class="proof">Explore context →</div></a></div></div></section>

{framework_teaser()}

<section class="section white"><div class="container"><div class="head"><div><p class="eyebrow">External perspective</p><h2>What colleagues say about working with me.</h2></div><p>Selected recommendations from people who worked with me in different roles and organizational contexts.</p></div><div class="principles"><article class="principle"><span>Direct manager · Volvo Trucks</span><h3>Claes Sandros</h3><p><strong>Acting Head of Data and Vice President Data, Analytics &amp; AI, Volvo Trucks</strong></p><p style="font:500 18px/1.5 Georgia,serif;color:var(--ink);margin-top:20px">“What truly impressed me was his ability to combine deep analytical knowledge with strategic thinking and a collaborative mindset.”</p><div class="proof"><a href="{CLAES_LINKEDIN}" target="_blank" rel="noopener" data-hq-event="reference_claes_home">LinkedIn profile ↗</a></div></article><article class="principle"><span>Senior cross-functional colleague · Volvo Group</span><h3>Anna Börjesson Sandberg</h3><p><strong>VP, Digital Transformation, Volvo Group Trucks Technology</strong></p><p style="font:500 18px/1.5 Georgia,serif;color:var(--ink);margin-top:20px">“Jair continuously wanted to move towards the future of Data and AI and could always explain the purpose and next possible steps.”</p><div class="proof"><a href="{ANNA_LINKEDIN}" target="_blank" rel="noopener" data-hq-event="reference_anna_home">LinkedIn profile ↗</a></div></article><article class="principle"><span>AI colleague · Volvo</span><h3>Kumara Datta</h3><p><strong>AI Strategy &amp; Adoption / Product Owner – GenAI Hub, Volvo</strong></p><p style="font:500 18px/1.5 Georgia,serif;color:var(--ink);margin-top:20px">“Jair has a rare ability to translate complex AI and data concepts into clear, actionable insights that resonate with both technical and business stakeholders.”</p><div class="proof"><a href="{KUMARA_LINKEDIN}" target="_blank" rel="noopener" data-hq-event="reference_kumara_home">LinkedIn profile ↗</a></div></article><article class="principle"><span>Former colleague</span><h3>Jim Edwards</h3><p><strong>Director of Digital, Innovation &amp; Platforms</strong></p><p style="font:500 18px/1.5 Georgia,serif;color:var(--ink);margin-top:20px">“He’s incredibly good at bringing people along on the journey and explaining the benefits of what AI can bring to an organization.”</p><div class="proof"><a href="{JIM_LINKEDIN}" target="_blank" rel="noopener" data-hq-event="reference_jim_home">LinkedIn profile ↗</a></div></article></div></div></section>

<section class="cta"><div class="container ctain"><div><h2>The useful question is usually what has to be true next.</h2><p>I have seen technically promising AI initiatives stall because responsibility was unclear long before the technology became the real problem. My work is often about making those dependencies visible enough for leadership teams to make a better decision.</p></div><div class="actions"><a class="btn ghost" href="?page=contact" target="_self" data-hq-event="contact_home_final">Discuss a leadership opportunity →</a><a class="btn ghost" href="{LINKEDIN}" target="_blank" rel="noopener" data-hq-event="linkedin_home_final">LinkedIn ↗</a></div></div></section>
</main>{footer()}'''
