from __future__ import annotations

from site_assets import CV_URI, EMAIL, LINKEDIN, ABOUT_BW_URI
from site_components import nav, footer, CV_DOWNLOAD_NAME


def contact() -> str:
    cv = f'<a href="{CV_URI}" download="{CV_DOWNLOAD_NAME}" data-hq-event="cv_download_contact">Download CV ↓</a>' if CV_URI else ""
    return f'''{nav("contact")}<main><section class="pagehero"><div class="container"><p class="eyebrow">Contact</p><h1>Discuss a leadership opportunity.</h1><p>My strongest fit is in senior AI, Data and Analytics leadership where strategy, portfolio, governance, adoption and operating capability have to work together.</p></div></section><section class="section paper"><div class="container contactgrid"><div><p class="eyebrow">Broad areas of fit</p><h2>Start with the leadership problem, not a long list of titles.</h2><p>The useful question is usually what the organization is trying to change and where the current AI or data capability is getting stuck. A few contexts where my experience is particularly relevant:</p><div class="focus"><div>Enterprise AI &amp; Data leadership</div><div>AI transformation and adoption</div><div>AI / Data operating models and Centers of Excellence</div><div>AI governance and Responsible AI</div><div>AI portfolio and value leadership</div><div>Selected advisory or interim mandates</div></div><p>Based in Gothenburg, Sweden, with experience in international and cross-border environments.</p></div><aside class="contactcard"><span>Direct contact</span><a href="mailto:{EMAIL}" data-hq-event="email_contact">{EMAIL}</a><a href="{LINKEDIN}" target="_blank" rel="noopener" data-hq-event="linkedin_contact">LinkedIn ↗</a>{cv}<p>Email or LinkedIn is the easiest way to reach me.</p></aside></div></section><section class="section white"><div class="container contactvisual"><div><p class="eyebrow">A useful first conversation</p><h2>What is the mandate expected to make possible?</h2><p>The most useful context is what the organization is trying to change, what evidence already exists, where ownership or capability is unclear and what accountability the role is expected to carry. That is usually enough to establish quickly whether my experience is relevant.</p></div><div class="contactportrait"><img src="{ABOUT_BW_URI}" alt="Jair Ribeiro" loading="lazy" decoding="async"></div></div></section></main>{footer()}'''
