from __future__ import annotations

from site_assets import CV_URI, HERO_URI, LINKEDIN
from site_components import nav, footer, CV_DOWNLOAD_NAME
from site_artifacts import framework_teaser
from career_facts import PROFILE_TECH_YEARS, VOLVO_AI_INITIATIVES, VOLVO_WORKFLOW_SCOPE


CLAES_LINKEDIN = "https://se.linkedin.com/in/claes-sandros-1a795512"
ANNA_LINKEDIN = "https://se.linkedin.com/in/annaborjesson"
KUMARA_LINKEDIN = "https://in.linkedin.com/in/kumara-datta"
JIM_LINKEDIN = "https://www.linkedin.com/in/james-edwards-7233b8152"


def home() -> str:
    return f'''{nav("home")}<main>
<section class="hero"><div class="container heroin"><div><p class="eyebrow">Enterprise AI · Data · Analytics</p><h1>Jair Ribeiro<span>Enterprise AI &amp; Data Leader</span></h1><p class="deck">I lead enterprise AI &amp; Data work where strategy has to become operating capability — clear priorities, ownership, adoption, governance and measurable business value.</p><p class="context">Based in Gothenburg · Sweden / Nordic scope · Gothenburg hybrid or Sweden-based remote · Available to start immediately</p><div class="actions"><a class="btn primary" href="?page=impact" target="_self" data-hq-event="impact_home">Selected experience →</a><a class="btn text" href="?page=ai-data-governance" target="_self" data-hq-event="governance_home">AI &amp; Data Governance →</a><a class="btn text" href="{CV_URI}" download="{CV_DOWNLOAD_NAME}" data-hq-event="cv_download_home">Download CV ↓</a></div></div><div class="portrait"><img src="{HERO_URI}" alt="Jair Ribeiro contributing to an executive AI panel" loading="eager" fetchpriority="high" decoding="async"><div class="note"><span>Operating perspective</span><strong>AI becomes useful when priorities, ownership and adoption are clear enough to support better business decisions.</strong></div></div></div><div class="company"><div class="container"><span>Experience across</span><b>Volvo Group</b><b>MSX International</b><b>Kimberly-Clark</b><b>IBM</b><b>HPE</b></div></div></section>

<section class="section white"><div class="container"><div class="head"><div><p class="eyebrow">Leadership focus</p><h2>Enterprise AI and Data leadership, from strategic priorities to operating capability.</h2></div><p>The common thread is moving from ambition to clearer choices, ownership and adoption — with enough structure to scale without adding unnecessary complexity.</p></div><div class="grid3"><article class="card"><span class="org">Enterprise AI strategy &amp; scaling</span><h3>Focus the portfolio on business value.</h3><p>Connect business priorities with AI opportunities, investment choices, ownership and the operating model needed to move from isolated pilots into sustained use — including Microsoft 365 Copilot and agent initiatives where they fit the work.</p></article><article class="card"><span class="org">Data &amp; Analytics leadership</span><h3>Strengthen the foundations behind decisions.</h3><p>Bring data strategy, analytics, governance and business ownership together so information and AI can support decisions at enterprise scale.</p></article><article class="card"><span class="org">Governance &amp; operating model</span><h3>Make accountability practical.</h3><p>Clarify decision rights, lifecycle responsibilities and proportionate controls so teams can move at the right pace with clearer accountability.</p></article></div><div class="prooflist" style="margin-top:30px"><div class="proofitem"><strong>{PROFILE_TECH_YEARS} years</strong> — enterprise technology experience across infrastructure, cloud, consulting, Data &amp; Analytics and AI.</div><div class="proofitem"><strong>{VOLVO_AI_INITIATIVES} AI initiatives, PoCs and projects</strong> — business-requirement, product and stakeholder work across a broad Volvo AI portfolio; at Volvo Trucks, this included Microsoft 365 Copilot and agent initiatives plus AI solutions introduced across {VOLVO_WORKFLOW_SCOPE}.</div><div class="proofitem"><strong>PoC → repeatable capability</strong> — at MSX International, portfolio visibility, lifecycle stages, ownership and data-governance foundations supported a clearer path from experimentation toward enterprise capability.</div></div><div class="actions"><a class="btn dark" href="?page=impact" target="_self" data-hq-event="impact_focus_home">View selected experience →</a><a class="btn dark" href="?page=ai-data-governance" target="_self" data-hq-event="governance_focus_home">Governance evidence →</a><a class="btn dark" href="?page=certifications" target="_self" data-hq-event="credentials_focus_home">Credentials &amp; verification →</a></div><p class="muted" style="margin:20px 0 0"><strong>Adoption in practice:</strong> GenAI, Copilot and agent work is treated as workflow and operating change — what changes in ownership, decisions and day-to-day use, not AI activity as an end in itself.</p></div></section>

<section class="section paper"><div class="container"><div class="head"><div><p class="eyebrow">Selected experience</p><h2>From value discovery to adoption and enterprise AI &amp; Data foundations.</h2></div><p>Across these roles, the pattern is consistent: start with the business problem, make the AI or Data decision explicit, then shape the ownership, workflow and controls needed for sustained use.</p></div><div class="thoughts" style="grid-template-columns:repeat(auto-fit,minmax(min(100%,300px),1fr));gap:18px"><article class="card"><span class="org">Volvo Group / Volvo Trucks</span><h3>Connecting enterprise AI adoption with real business workflows.</h3><p><strong>Challenge:</strong> AI opportunities across commercial operations and enterprise communities sat inside different workflows, data conditions and stakeholder environments.</p><p><strong>What I shaped:</strong> Across my Volvo AI roles, I led business-requirement, product and stakeholder work across a broad AI portfolio. At Volvo Trucks, I led Microsoft 365 Copilot and agent initiatives alongside AI solutions moving into {VOLVO_WORKFLOW_SCOPE} workflows, with the use cases targeting cycle time, cost and practical adoption.</p><div class="proof">Warranty · sales · aftermarket · AI solutions &amp; agents · cross-functional use · operational adoption</div></article><article class="card"><span class="org">MSX International</span><h3>Building the foundations for an enterprise AI &amp; Data capability.</h3><p><strong>Challenge:</strong> An emerging CoE needed clearer portfolio visibility, decision rights, governance and data foundations while the organization was still building readiness.</p><p><strong>What I shaped:</strong> I established the CoE as a business-facing capability engine, creating portfolio and lifecycle structure, a 2026–2027 maturity roadmap and data-governance foundations while clarifying capability gaps and roles.</p><div class="proof">2026–2027 roadmap · portfolio visibility · lifecycle roles · stewardship foundations · capability gaps</div></article><article class="card"><span class="org">Kimberly-Clark</span><h3>Making EMEA AI opportunities comparable without losing context.</h3><p><strong>Challenge:</strong> Functions had different problems, data realities and readiness, making AI opportunities difficult to compare on a like-for-like basis.</p><p><strong>What I shaped:</strong> I led value discovery and realization across EMEA, starting from the business problem and value hypothesis before moving to the technical solution so business and data-science teams could compare opportunities on a more consistent basis.</p><div class="proof">EMEA · reporting to CDAO · supply chain · manufacturing · logistics · sales · marketing</div></article></div><div class="actions"><a class="btn dark" href="?page=impact" target="_self" data-hq-event="impact_cases">See the full experience →</a></div></div></section>

{framework_teaser()}

<section class="section white"><div class="container"><div class="head"><div><p class="eyebrow">References</p><h2>Comments from people I worked with.</h2></div><p>Two examples from a direct manager and a senior cross-functional colleague.</p></div><div class="principles"><article class="principle"><span>Direct manager · Volvo Trucks</span><h3>Claes Sandros</h3><p><strong>Acting Head of Data and Vice President Data, Analytics &amp; AI, Volvo Trucks</strong></p><p style="font:500 18px/1.5 Georgia,serif;color:var(--ink);margin-top:20px">“What truly impressed me was his ability to combine deep analytical knowledge with strategic thinking and a collaborative mindset.”</p><div class="proof"><a href="{CLAES_LINKEDIN}" target="_blank" rel="noopener" data-hq-event="reference_claes_home">LinkedIn profile ↗</a></div></article><article class="principle"><span>Senior cross-functional colleague · Volvo Group</span><h3>Anna Börjesson Sandberg</h3><p><strong>VP, Digital Transformation, Volvo Group Trucks Technology</strong></p><p style="font:500 18px/1.5 Georgia,serif;color:var(--ink);margin-top:20px">“Jair continuously wanted to move towards the future of Data and AI and could always explain the purpose and next possible steps.”</p><div class="proof"><a href="{ANNA_LINKEDIN}" target="_blank" rel="noopener" data-hq-event="reference_anna_home">LinkedIn profile ↗</a></div></article></div></div></div></section>

<section class="cta"><div class="container ctain"><div><h2>For enterprise AI and Data mandates.</h2><p>Experience across strategy, adoption, operating models, governance and Data &amp; Analytics in international enterprise environments.</p></div><div class="actions"><a class="btn ghost" href="?page=contact" target="_self" data-hq-event="contact_home_final">Contact →</a><a class="btn ghost" href="{LINKEDIN}" target="_blank" rel="noopener" data-hq-event="linkedin_home_final">LinkedIn ↗</a></div></div></section>
</main>{footer()}'''
