from __future__ import annotations

from site_assets import CV_URI, ABOUT_BW_URI
from site_components import nav, footer, opportunity, CV_DOWNLOAD_NAME


def about() -> str:
    cv = f'<a class="btn dark" href="{CV_URI}" download="{CV_DOWNLOAD_NAME}" data-hq-event="cv_download_about">Download full CV ↓</a>' if CV_URI else ""
    return f'''{nav("about")}<main>
<section class="pagehero"><div class="container"><p class="eyebrow">About</p><h1>A career that moved from enterprise technology foundations into business-facing AI, Data and Analytics leadership.</h1><p>20+ years in enterprise technology, including 8+ years in AI, data and analytics leadership. The recurring work has been helping organizations connect ambition with the conditions required to make it useful: priorities, responsibility, data, governance, everyday use and value.</p></div></section>

<section class="section white"><div class="container editorial-split"><div><p class="eyebrow">Professional arc</p><h2>The technology changed. The leadership questions became clearer.</h2><p class="muted">My early career was grounded in enterprise systems, infrastructure, cloud, consulting and client-facing technology work. That period taught me something I still rely on: a technical choice always carries operating, cost, risk and stakeholder consequences once it leaves the lab.</p><p class="muted">From 2017 onward, AI moved closer to the center of my work. IBM Watson solution design led into business-facing AI roles at Volvo Group, then EMEA AI strategy at Kimberly-Clark, AI and analytics adoption at Volvo Trucks, and most recently the foundations of an AI &amp; Data Center of Excellence at MSX International.</p><p class="muted">What kept repeating was not a specific model or platform. It was the gap between technical possibility and enterprise use. I have seen promising initiatives slow down because the problem was poorly framed, responsibility was implicit, data was not trusted, governance arrived too late, or the people expected to use the capability were never brought into the decision.</p><p class="muted">That is why my leadership perspective is increasingly about the system around AI. I am interested in how organizations make better choices about where to focus, what has to be true before scaling, where each decision belongs and how technical possibility connects to everyday work.</p></div><div class="editorial-photo portrait"><img src="{ABOUT_BW_URI}" alt="Jair Ribeiro portrait" loading="lazy" decoding="async"></div></div><div class="container"><div class="timeline"><div class="trow"><b>2004–2017</b><div><strong>Enterprise technology foundations</strong><span>Infrastructure, enterprise systems, consulting, cloud and client-facing technology work across Italy, Brazil and Poland.</span></div></div><div class="trow"><b>2017–2021</b><div><strong>From technology delivery to AI business translation</strong><span>IBM Watson solution design followed by Volvo Group AI CoE work engaging 1,500+ practitioners, delivering 100+ sessions and supporting 100+ AI initiatives, PoCs and projects.</span></div></div><div class="trow"><b>2021–2025</b><div><strong>AI strategy, adoption and analytics leadership</strong><span>EMEA AI value discovery at Kimberly-Clark, reporting directly to the CDAO, followed by Volvo Trucks adoption work across warranty, sales and aftermarket.</span></div></div><div class="trow"><b>2025–2026</b><div><strong>Building the structures around AI &amp; Data</strong><span>CoE portfolio and lifecycle governance, a 2026–2027 maturity roadmap, data-governance foundations and capability design at MSX International.</span></div></div></div></div></section>

<section class="section soft"><div class="container"><div class="head"><div><p class="eyebrow">How I lead</p><h2>Collaborative in understanding. Clear when decisions need to be made.</h2></div><p>Business, technology, governance and users often look at the same AI initiative through different lenses: opportunity, dependencies, risk and disruption to the work. Much of my role has been making those perspectives visible early enough for the organization to decide with fewer hidden assumptions.</p></div><div class="principles"><div class="principle"><span>01</span><h3>Make complexity understandable</h3><p>I separate what is known, what is assumed and what still needs to be proven. That gives teams enough structure to decide without turning uncertainty into bureaucracy.</p></div><div class="principle"><span>02</span><h3>Work across boundaries</h3><p>Most AI problems sit between business, data, technology, governance and people. I make the dependencies visible and translate the consequences of one discipline’s choices for the others.</p></div><div class="principle"><span>03</span><h3>Make disagreement useful</h3><p>I surface disagreement early, explain the trade-off and make a recommendation without pretending uncertainty has disappeared. Useful challenge is more valuable than artificial certainty.</p></div><div class="principle"><span>04</span><h3>Build capability, not dependency</h3><p>I prefer reusable patterns, clear decision rights and stronger internal judgment over a central team that has to approve or deliver everything. Scale improves when the organization learns to act for itself.</p></div></div></div></section>

<section class="section navy"><div class="container"><div class="head"><div><p class="eyebrow">Enterprise AI perspective</p><h2>AI scales as a system, not as a model.</h2></div><p>That view comes from seeing the same pattern across different organizations: technically promising work becomes useful only when priorities, responsibility, data, governance and adoption line up well enough for people to act on it.</p></div><p class="flowcopy">For me, this is less a framework than a way of reading the organization around the technology: where the real constraint sits, which decision is still implicit, and what has to change before the next step is credible.</p></div></section>

<section class="section white"><div class="container twocol"><div><p class="eyebrow">Technical &amp; enterprise fluency</p><h2>Technical judgment in service of leadership decisions.</h2><p class="muted">My technical background helps me engage engineers, architects and data specialists, understand the consequences of architecture and data choices, and challenge trade-offs around scalability, security, cost, governance and operational readiness. Specialist depth should remain with the specialists responsible for those decisions.</p><p class="muted">The value I add is knowing which technical questions matter for the business decision, where a technical constraint changes the answer, and when specialist depth should lead.</p></div><div><div class="chips"><span>Enterprise AI architecture</span><span>GenAI</span><span>Agentic AI</span><span>Analytics</span><span>Data platforms</span><span>Data quality</span><span>Stewardship</span><span>Cloud</span><span>MLOps principles</span><span>Security</span><span>AI risk</span><span>Governance</span><span>Scalability</span><span>Vendor evaluation</span><span>Cost / accuracy trade-offs</span><span>Operational readiness</span></div><div class="grid3" style="margin-top:24px"><article class="card"><span class="org">Architecture</span><h3>Can this survive the enterprise?</h3><p>I look beyond model quality to integration, scalability, security, maintainability and the cost of turning a promising prototype into something the organization can operate.</p></article><article class="card"><span class="org">Data &amp; trust</span><h3>Is the foundation credible?</h3><p>Data access, quality, semantics, stewardship and lineage shape both technical performance and organizational trust. Weak foundations usually reappear later as adoption or governance problems.</p></article><article class="card"><span class="org">Risk &amp; economics</span><h3>Is the trade-off justified?</h3><p>Accuracy, autonomy, cost, control and user value move together. The useful question is what level of capability is justified for this decision, user and risk.</p></article></div></div></div></section>

<section class="section soft"><div class="container"><div class="head"><div><p class="eyebrow">Credentials &amp; perspective</p><h2>Formal study matters when it sharpens practical judgment.</h2></div><p>My academic work complements rather than replaces operating experience. The focus has been on how AI can be adopted responsibly inside real organizations, where governance, trust, incentives and business pressure exist at the same time.</p></div><div class="grid3"><div class="card"><span class="org">Education</span><h3>MSc, Artificial Intelligence</h3><p>Research focused on Responsible AI adoption in global enterprises and the tension between innovation, governance and trust.</p></div><div class="card"><span class="org">Research lens</span><h3>Responsible adoption, not compliance-only governance</h3><p>I am interested in governance as part of how the organization works: how responsibility, proof, risk and escalation can increase trust and decision quality without disconnecting control from the work.</p></div><div class="card"><span class="org">Recognition</span><h3>Thinkers360 Top 50</h3><p>Global Thought Leaders &amp; Influencers on Emerging Technology, 2023.</p></div></div></div></section>

<section class="section white"><div class="container"><div class="head"><div><p class="eyebrow">Languages &amp; working context</p><h2>International experience, with Sweden as the professional base.</h2></div><p>Based in Gothenburg, with experience across Sweden, Poland, Italy and Brazil and work in global organizations. That background has made me comfortable adapting how I communicate and lead without changing the standard of reasoning or accountability behind the decision.</p></div><div class="chips"><span>Portuguese — native/bilingual</span><span>Italian — native/bilingual</span><span>English — full professional</span><span>Spanish — professional</span><span>Polish — limited working</span><span>Swedish — elementary</span></div><div class="actions">{cv}</div></div></section>
{opportunity()}</main>{footer()}'''
