from __future__ import annotations

"""Browser-safe delivery for the canonical public CV.

Streamlit Community Cloud guarantees static serving for repository-backed files,
but runtime-generated replacements are not guaranteed to become the bytes served
from /app/static. To avoid stale or mismatched PDF downloads, every website CTA
uses the exact in-memory PDF bytes generated by site_cv as a base64 data URI.
The downloaded file remains an ordinary PDF; the data URI is only the transport.
"""

import base64

import site_assets
from site_cv import CV_BYTES

PDF_DATA_URI = "data:application/pdf;base64," + base64.b64encode(CV_BYTES).decode("ascii")

# Page modules import CV_URI after this module is loaded by app.py.
site_assets.CV_URI = PDF_DATA_URI
