from __future__ import annotations


def framework_teaser() -> str:
    return '''<section class="section soft"><div class="container"><div class="head"><div><p class="eyebrow">How I structure enterprise AI decisions</p><h2>See the thinking behind the leadership claims.</h2></div><p>A CV can describe operating models, governance and scale-readiness. The website can show how I structure those decisions. These are sanitized, generic reconstructions of patterns I have used in enterprise AI work — no confidential internal material.</p></div><div class="prooflist"><div class="proofitem"><strong>AI portfolio lifecycle</strong> — from opportunity framing to monitored enterprise value.</div><div class="proofitem"><strong>Enterprise AI operating model</strong> — how business ownership, delivery, data, governance, adoption and value connect.</div><div class="proofitem"><strong>Pilot → enterprise scale framework</strong> — the evidence I look for before a promising experiment earns broader investment.</div><div class="proofitem"><strong>Governance decision matrix</strong> — matching the level of control to consequence and uncertainty.</div></div><div class="actions"><a class="btn dark" href="?page=impact#leadership-frameworks" target="_self" data-hq-event="frameworks_home">See the leadership frameworks →</a></div></div></section>'''


def leadership_frameworks() -> str:
    return '''<section id="leadership-frameworks" class="section navy"><div class="container"><div class="head"><div><p class="eyebrow">Sanitized leadership artifacts</p><h2>How I structure enterprise AI decisions.</h2></div><p>These frameworks are generic reconstructions of recurring patterns from my enterprise AI work. They are deliberately sanitized: they contain no confidential company data, internal templates or proprietary decision thresholds. Their purpose is to show approximately how I think about portfolio choices, operating models, governance and scale.</p></div>

<div style="padding:8px 0 44px"><p class="eyebrow">01 · AI portfolio lifecycle</p><h3 style="margin:0 0 12px;font:500 32px/1.12 Georgia,serif;color:#fff">Move opportunities through evidence, not enthusiasm.</h3><p style="max-width:880px;color:#b8c2cf;line-height:1.7">The lifecycle separates an interesting idea from an investable enterprise capability. Each stage should reduce a different kind of uncertainty before more money, integration effort or organizational dependency is added.</p><div class="flow" style="margin-top:24px"><div class="step"><span>01</span><strong>Frame the problem</strong></div><div class="step"><span>02</span><strong>Qualify the opportunity</strong></div><div class="step"><span>03</span><strong>Discover value &amp; feasibility</strong></div><div class="step"><span>04</span><strong>Experiment / pilot</strong></div><div class="step"><span>05</span><strong>Prove scale-readiness</strong></div><div class="step"><span>06</span><strong>Operate &amp; track value</strong></div></div><p class="flowcopy">A stage is not a ceremony. It is a decision point: what has been learned, what remains uncertain, who owns the next risk, and whether the evidence justifies more commitment.</p></div>

<div style="padding:44px 0;border-top:1px solid rgba(255,255,255,.14)"><p class="eyebrow">02 · Enterprise AI operating model</p><h3 style="margin:0 0 12px;font:500 32px/1.12 Georgia,serif;color:#fff">Keep one value chain across six different accountabilities.</h3><p style="max-width:880px;color:#b8c2cf;line-height:1.7">The operating model works when ownership is explicit but the pieces remain connected. No single central team should have to own every business, technical, data, risk and adoption decision.</p><div class="grid3" style="margin-top:24px"><article class="card"><span class="org">Business</span><h3>Priorities &amp; outcomes</h3><p>Own the business problem, expected outcome and changed decision or workflow.</p></article><article class="card"><span class="org">Portfolio / CoE</span><h3>Orchestration &amp; choices</h3><p>Compare opportunities, expose dependencies and keep investment focused on the work with credible evidence.</p></article><article class="card"><span class="org">Product / Delivery</span><h3>Capability &amp; iteration</h3><p>Translate the problem into a usable product or service and learn through delivery.</p></article><article class="card"><span class="org">Data &amp; Architecture</span><h3>Foundation &amp; scale</h3><p>Make data quality, integration, security, cost and maintainability visible early.</p></article><article class="card"><span class="org">Governance / Risk</span><h3>Evidence &amp; escalation</h3><p>Define what must be proven, which decisions need review and where higher consequence changes the control level.</p></article><article class="card"><span class="org">Adoption &amp; Value</span><h3>Behavior &amp; outcomes</h3><p>Track whether people use the capability, workflows change and the expected value is actually appearing.</p></article></div></div>

<div style="padding:44px 0;border-top:1px solid rgba(255,255,255,.14)"><p class="eyebrow">03 · Pilot → enterprise scale</p><h3 style="margin:0 0 12px;font:500 32px/1.12 Georgia,serif;color:#fff">A successful pilot is evidence of possibility — not yet evidence of scale.</h3><p style="max-width:880px;color:#b8c2cf;line-height:1.7">Before scaling, I want evidence across the system around the model. A weak dimension does not always mean stop, but it should change the investment decision, scope or mitigation plan.</p><div class="grid3" style="margin-top:24px"><article class="card"><span class="org">01 · Business ownership</span><h3>Is someone accountable for the outcome?</h3><p>Named business owner, defined workflow or decision, and clear responsibility for adoption and benefits.</p></article><article class="card"><span class="org">02 · Value hypothesis</span><h3>Is the value worth scaling for?</h3><p>A measurable problem, credible baseline and a reason the expected improvement matters strategically or economically.</p></article><article class="card"><span class="org">03 · Data readiness</span><h3>Can the foundation support repeatable use?</h3><p>Access, quality, semantics, ownership and lineage are sufficient for the intended scale and consequence.</p></article><article class="card"><span class="org">04 · Technical readiness</span><h3>Can it survive the enterprise?</h3><p>Architecture, integration, security, performance, supportability and cost are understood beyond the prototype environment.</p></article><article class="card"><span class="org">05 · Governance readiness</span><h3>Is the risk understood and owned?</h3><p>Relevant controls, evidence, escalation and accountability exist for the intended users and consequences.</p></article><article class="card"><span class="org">06 · Adoption readiness</span><h3>Will the organization actually use it?</h3><p>Workflow fit, user confidence, process change, support and operating ownership are credible enough to sustain use.</p></article></div><p class="flowcopy">Scale when the remaining uncertainty is explicit, owned and proportionate to the expected value — not because the demo worked.</p></div>

<div style="padding:44px 0 0;border-top:1px solid rgba(255,255,255,.14)"><p class="eyebrow">04 · Governance decision matrix</p><h3 style="margin:0 0 12px;font:500 32px/1.12 Georgia,serif;color:#fff">Match governance intensity to consequence and uncertainty.</h3><p style="max-width:880px;color:#b8c2cf;line-height:1.7">Not every AI use case needs the same process. The control model should become stronger when the potential consequence is higher, the behavior is less predictable, or both.</p><div class="principles" style="margin-top:24px"><article class="principle"><span>Low consequence · Low uncertainty</span><h3>Enable local experimentation</h3><p>Use lightweight standards, clear acceptable-use boundaries and normal team ownership. Avoid central review becoming the bottleneck.</p></article><article class="principle"><span>High consequence · Low uncertainty</span><h3>Apply standard enterprise controls</h3><p>Require clear ownership, testing, security, privacy and operational controls appropriate to the business impact.</p></article><article class="principle"><span>Low consequence · High uncertainty</span><h3>Bound the experiment</h3><p>Limit exposure, instrument the learning, keep human review close and define what evidence would justify broader use.</p></article><article class="principle"><span>High consequence · High uncertainty</span><h3>Escalate before scale</h3><p>Use stronger multidisciplinary review, explicit risk acceptance, evidence thresholds and a clear decision owner before broader deployment.</p></article></div><p class="flowcopy">The objective is not to minimize governance. It is to put the right governance where it changes the quality of the decision.</p></div>

<p style="margin:38px 0 0;color:#8f9bad;font-size:11px;line-height:1.65">Illustrative frameworks based on enterprise practice. Recreated in generic form for this site; no confidential company material, internal thresholds or proprietary templates are reproduced.</p></div></section>'''
